#
# Copyright 2011 Matt Kenney
#
# This file is part of Feedsqueeze.
#
# Feedsqueeze is free software: you can redistribute it and/or modify it under
# the terms of the GNU Affero General Public License as published by the Free
# Software Foundation, either version 3 of the License, or (at your option) any
# later version.
#
# Feedsqueeze is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public License for more
# details.
#
# You should have received a copy of the GNU Affero General Public License
# along with Feedsqueeze.  If not, see <http://www.gnu.org/licenses/>.
#
application: feedsqueeze
version: 1
runtime: python
api_version: 1

#error_handlers:
#  - file: default_error.html

handlers:
- url: /admin/.*
  script: handler.py
  login: admin
  secure: always

- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: /css/
  static_dir: static/css

- url: /images/
  static_dir: static/images

- url: /js/
  static_dir: static/js

- url: /.*
  script: handler.py
  login: required
  secure: always
